"""add message

Revision ID: 3a1c6b9b04b1
Revises: 0fb20df71005
Create Date: 2026-08-20 21:43:57.686128

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src.core.types

# revision identifiers, used by Alembic.
revision: str = "3a1c6b9b04b1"
down_revision: Union[str, Sequence[str], None] = "0fb20df71005"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "messages",
        sa.Column(
            "code",
            sa.Enum(
                "REGISTER", "VERIFY", "RESET_PASSWORD", name="messagecode"
            ),
            nullable=False,
        ),
        sa.Column("subject", sa.String(length=120), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_messages_code"), "messages", ["code"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_messages_code"), table_name="messages")
    op.drop_table("messages")
    # ### end Alembic commands ###
