"""add landing

Revision ID: cc0f07874517
Revises: d70fc79841c7
Create Date: 2026-08-16 18:00:01.869020

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src.core.types

# revision identifiers, used by Alembic.
revision: str = "cc0f07874517"
down_revision: Union[str, Sequence[str], None] = "d70fc79841c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "landing",
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("subtitle", sa.String(length=250), nullable=True),
        sa.Column("hero_image", src.core.types.FileType(), nullable=True),
        sa.Column("about_title", sa.String(length=120), nullable=True),
        sa.Column("about_text", sa.Text(), nullable=True),
        sa.Column("address", sa.String(length=250), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("email", sa.String(length=256), nullable=True),
        sa.Column("working_hours", sa.String(length=250), nullable=True),
        sa.Column("map_url", sa.String(length=500), nullable=True),
        sa.Column("vk_url", sa.String(length=500), nullable=True),
        sa.Column("reviews_url", sa.String(length=500), nullable=True),
        sa.Column("has_wifi", sa.Boolean(), nullable=False),
        sa.Column("has_sockets", sa.Boolean(), nullable=False),
        sa.Column("has_terrace", sa.Boolean(), nullable=False),
        sa.Column("is_pet_friendly", sa.Boolean(), nullable=False),
        sa.Column("has_takeaway", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("id = 1", name="ck_landing_singleton"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("landing")
    # ### end Alembic commands ###
