"""init db

Revision ID: f9a32a517b00
Revises:
Create Date: 2026-08-15 14:50:39.886549

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f9a32a517b00"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "positions",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("salary_min", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("salary_max", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "salary_min IS NULL OR salary_max IS NULL OR salary_max >= salary_min",
            name="ck_positions_salary_range",
        ),
        sa.CheckConstraint(
            "salary_min IS NULL OR salary_min >= 0",
            name="ck_positions_salary_min_non_negative",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_positions_name"), "positions", ["name"], unique=True)
    op.create_table(
        "employees",
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("patronymic", sa.String(length=100), nullable=True),
        sa.Column(
            "employment_type",
            sa.Enum(
                "FULL",
                "PARTIAL",
                "SHIFT",
                "PROBATION",
                "CONTRACT",
                name="employmenttype",
            ),
            nullable=False,
        ),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("email", sa.String(length=256), nullable=True),
        sa.Column("salary", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("hired_at", sa.Date(), nullable=True),
        sa.Column("fired_at", sa.Date(), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("position_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("salary >= 0", name="ck_employees_salary_non_negative"),
        sa.ForeignKeyConstraint(["position_id"], ["positions.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_employees_email"), "employees", ["email"], unique=True)
    op.create_index(
        op.f("ix_employees_employment_type"),
        "employees",
        ["employment_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_employees_last_name"), "employees", ["last_name"], unique=False
    )
    op.create_index(op.f("ix_employees_phone"), "employees", ["phone"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_employees_phone"), table_name="employees")
    op.drop_index(op.f("ix_employees_last_name"), table_name="employees")
    op.drop_index(op.f("ix_employees_employment_type"), table_name="employees")
    op.drop_index(op.f("ix_employees_email"), table_name="employees")
    op.drop_table("employees")
    op.drop_index(op.f("ix_positions_name"), table_name="positions")
    op.drop_table("positions")
    # ### end Alembic commands ###
